CREATE TABLE CLIENTE
(
    NUMCLIENTE INT(10) AUTO_INCREMENT,
    SALDO INT(10),
    DESCUENTO INT(10),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (NUMCLIENTE)
);

CREATE TABLE FABRICA
(
    NUMFABRICA INT(10) AUTO_INCREMENT,
    TELEFONO INT(10),
    CONSTRAINT PK_FABRICA PRIMARY KEY (NUMFABRICA)
);

CREATE TABLE ARTICULO
(
    NUMARTICULO INT(10) AUTO_INCREMENT,
    DESCRIPCION VARCHAR(25),
    CONSTRAINT PK_ARTICULO PRIMARY KEY (NUMARTICULO)
);

CREATE TABLE DIRECCION
(
    CODDIRECCION VARCHAR(15),
    VIA VARCHAR(10),
    NOMBREVIA VARCHAR(15),
    NUMERO INT(10),
    PISO INT(10),
    PORTAL VARCHAR(15),
    CODPOSTAL INT(10)
);

CREATE TABLE DISTRIBUYE
(
    NUMARTICULO INT(10),
    NUMFABRICA INT(10),
    CANTSUMINISTRO INT(10),
    EXISTENCIAS INT(10)
);

CREATE TABLE INCLUYE
(
    NUMPEDIDO INT(10),
    NUMARTICULO INT(10),
    CANTIDAD INT(10)
);

CREATE TABLE PEDIDO
(
    NUMPEDIDO INT(10),
    FECHA DATE,
    NUMCLIENTE INT(10),
    CODDIRECCION VARCHAR(15)
);

CREATE TABLE POSEE
(
    NUMCLIENTE INT(10),
    CODDIRECCION VARCHAR(15)
);



ALTER TABLE DIRECCION ADD CONSTRAINT PK_DIRECCION PRIMARY KEY (CODDIRECCION);

ALTER TABLE DISTRIBUYE ADD CONSTRAINT PK_DISTRIBUYE PRIMARY KEY (NUMARTICULO, NUMFABRICA);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK1_DISTRIBUYE FOREIGN KEY (NUMARTICULO) REFERENCES ARTICULO(NUMARTICULO);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK2_DISTRIBUYE FOREIGN KEY (NUMFABRICA) REFERENCES FABRICA(NUMFABRICA);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMPEDIDO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK1_PEDIDO FOREIGN KEY (NUMCLIENTE) REFERENCES CLIENTE(NUMCLIENTE);
ALTER TABLE PEDIDO ADD CONSTRAINT FK2_PEDIDO FOREIGN KEY (CODDIRECCION) REFERENCES DIRECCION(CODDIRECCION);

ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE PRIMARY KEY (NUMPEDIDO, NUMARTICULO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK1_INCLUYE FOREIGN KEY (NUMPEDIDO) REFERENCES PEDIDO(NUMPEDIDO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY (NUMARTICULO) REFERENCES ARTICULO(NUMARTICULO);


ALTER TABLE POSEE ADD CONSTRAINT PK_POSEE PRIMARY KEY (NUMCLIENTE, CODDIRECCION);
ALTER TABLE POSEE ADD CONSTRAINT FK1_POSEE FOREIGN KEY (NUMCLIENTE) REFERENCES CLIENTE(NUMCLIENTE);
ALTER TABLE POSEE ADD CONSTRAINT FK2_POSEE FOREIGN KEY (CODDIRECCION) REFERENCES DIRECCION(CODDIRECCION);

















