CREATE TABLE CLIENTE 
(
COD_CLIENTE VARCHAR2(10),
DNI VARCHAR(10),
NOMBRE VARCHAR2(10),
DIRECCION VARCHAR2(15),
TELEFONO NUMBER(10),
CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE COCHE
(
MATRICULA VARCHAR2(10),
MARCA VARCHAR2(10),
MODELO VARCHAR2(10),
COLOR VARCHAR2(10),
PRECIO_HORA NUMBER(10),
CONSTRAINT PK_COCHE PRIMARY KEY (MATRICULA)
);

CREATE TABLE RESERVA
(
NUMERO NUMBER(10),
FECHA_INICIO DATE,
FECHA_FIN DATE,
PRECIO_TOTAL NUMBER(10),
COD_CLIENTE VARCHAR2(10),
CONSTRAINT PK_RESERVA PRIMARY KEY (NUMERO),
CONSTRAINT FK1_RESERVA FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);

CREATE TABLE AVALA
(
AVALADO VARCHAR2(10),
AVALADOR VARCHAR2(10),
CONSTRAINT PK_AVALA PRIMARY KEY (AVALADO),
CONSTRAINT FK1_AVALA FOREIGN KEY (AVALADO) REFERENCES CLIENTE(COD_CLIENTE),
CONSTRAINT FK2_AVALA FOREIGN KEY (AVALADOR) REFERENCES CLIENTE(COD_CLIENTE)
);

CREATE TABLE INCLUYE 
(
NUMERO NUMBER(10),
MATRICULA VARCHAR2(10),
LITROS_GAS NUMBER(10),
CONSTRAINT PK_INCLUYE PRIMARY KEY (NUMERO,MATRICULA),
CONSTRAINT FK1_INCLUYE FOREIGN KEY (NUMERO) REFERENCES RESERVA(NUMERO),
CONSTRAINT FK2_INCLUYE FOREIGN KEY (MATRICULA) REFERENCES COCHE(MATRICULA)
);































