CREATE TABLE DIRECTOR
(
NOMBRE VARCHAR2(10),
NACIONALIDAD VARCHAR2(15),
CONSTRAINT PK_DIRECTOR PRIMARY KEY (NOMBRE)
);

CREATE TABLE ACTORES 
(
NOMBRE VARCHAR2(10),
NACIONALIDAD VARCHAR2(15),
SEXO VARCHAR2(5) DEFAULT 'S',
CONSTRAINT PK_ACTORES PRIMARY KEY (NOMBRE)
);

CREATE TABLE PELICULA
(
ID VARCHAR2(10),
TITULO VARCHAR2(10) NOT NULL,
PRODUCTORA VARCHAR2(10),
FECHA DATE,
DIRECTOR VARCHAR2(10),
CONSTRAINT PK_PELICULA PRIMARY KEY (ID),
CONSTRAINT FK1_PELICULA FOREIGN KEY (DIRECTOR) REFERENCES DIRECTOR(NOMBRE)
);

CREATE TABLE ACTUA
(
ACTOR VARCHAR2(10),
ID_PELI VARCHAR2(10),
PROTAGONISTA VARCHAR2(10) CHECK (protagonista IN ('SI', 'NO')),
CONSTRAINT PK_ACTUA PRIMARY KEY (ACTOR,ID_PELI),
CONSTRAINT FK1_ACTUA FOREIGN KEY (ACTOR) REFERENCES ACTORES(NOMBRE),
CONSTRAINT FK2_ACTUA FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID)
);

CREATE TABLE EJEMPLAR
(
ID_PELI VARCHAR2(10),
NUMERO NUMBER(10),
ESTADO VARCHAR2(10),
CONSTRAINT PK_EJEMPLAR PRIMARY KEY (ID_PELI,NUMERO),
CONSTRAINT FK1_EJEMPLAR FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID)
);

CREATE TABLE SOCIO
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(10) NOT NULL,
DIRECCION VARCHAR2(15),
TELEFONO NUMBER(10),
AVALADOR VARCHAR2(10),
CONSTRAINT PK_SOCIO PRIMARY KEY (DNI),
CONSTRAINT FK1_SOCIO FOREIGN KEY (AVALADOR) REFERENCES SOCIO(DNI)
);

CREATE TABLE ALQUILA
(
DNI VARCHAR2(10),
ID_PELI VARCHAR2(10),
NUMERO NUMBER(10),
FECHA_ALQUILER DATE,
FECHA_DEVOLUCION DATE,
CONSTRAINT PK_ALQUILA PRIMARY KEY (DNI,ID_PELI,NUMERO,FECHA_ALQUILER),
CONSTRAINT FK1_ALQUILA FOREIGN KEY (DNI) REFERENCES SOCIO(DNI),
CONSTRAINT FK2_ALQUILA FOREIGN KEY (ID_PELI,NUMERO) REFERENCES EJEMPLAR(ID_PELI,NUMERO)
);

ALTER TABLE ACTORES ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('M','H'));
















