CREATE TABLE CLIENTE
(
DNI VARCHAR(10),
NOMBRE VARCHAR(15),
DIRECCION VARCHAR(15),
LOCALIDAD VARCHAR(15),
FECHA_NAC DATE,
SEXO VARCHAR(5)
);

CREATE TABLE SUCURSAL
(
COD_SUCURSAL INT(10) AUTO_INCREMENT,
NOMBRE VARCHAR(15),
DIRECCION VARCHAR(15),
LOCALIDAD VARCHAR(15),
CONSTRAINT PK_SUCURSAL PRIMARY KEY (COD_SUCURSAL)
) AUTO_INCREMENT = 101;


CREATE TABLE CUENTA
(
COD_SUCURSAL INT(10),
COD_CUENTA VARCHAR(10)
);

CREATE TABLE TRANSACCION
(
COD_SUCURSAL INT(10),
COD_CUENTA VARCHAR(10),
NUM_TRANSACCION INT(10),
FECHA DATE,
CANTIDAD INT(10),
TIPO VARCHAR(10)
);

CREATE TABLE CLI_CUENTA
(
COD_SUCURSAL INT(10),
COD_CUENTA VARCHAR(10),
DNI VARCHAR(10)
);


ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI);



ALTER TABLE CUENTA ADD CONSTRAINT PK_CUENTA PRIMARY KEY (COD_SUCURSAL,COD_CUENTA);
ALTER TABLE CUENTA ADD CONSTRAINT FK1__CEUNTA FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL);

ALTER TABLE TRANSACCION ADD CONSTRAINT PK_TRANSSACICION PRIMARY KEY (COD_SUCURSAL,COD_CUENTA,NUM_TRANSACCION);
ALTER TABLE  TRANSACCION ADD CONSTRAINT FK1_TRANSACCION FOREIGN KEY (COD_SUCURSAL,COD_CUENTA) REFERENCES CUENTA(COD_SUCURSAL,COD_CUENTA);

ALTER TABLE CLI_CUENTA ADD CONSTRAINT PK_CLI_CUENTA PRIMARY KEY (COD_SUCURSAL,COD_CUENTA,DNI);
ALTER TABLE CLI_CUENTA ADD CONSTRAINT FK1_CLI_CUENTA FOREIGN KEY (COD_SUCURSAL,COD_CUENTA) REFERENCES CUENTA(COD_SUCURSAL,COD_CUENTA);
ALTER TABLE CLI_CUENTA ADD CONSTRAINT FK2_CLI_CUENTA FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI);
 


INSERT INTO SUCURSAL (NOMBRE) VALUES ("JAVIER");

select * from SUCURSAL ;






