CREATE TABLE ALUMNOS
(
NUM_MATRICULA NUMBER(10),
NOMBRE VARCHAR2(20),
FECHA_NACIMIENTO DATE,
TELEFONO NUMBER(10),
CONSTRAINT PK_ALUMNOS PRIMARY KEY (NUM_MATRICULA)
);

CREATE TABLE PROFESOR
(
ID_PROFESOR VARCHAR2(10),
NIF_P VARCHAR2(10),
NOMBRE VARCHAR2(10),
ESPECIALIDAD VARCHAR2(10),
TELEFONO NUMBER(10),
CONSTRAINT PK_PROFESOR PRIMARY KEY (ID_PROFESOR)
);

CREATE TABLE ASIGNATURA
(
COD_ASIGNATURA VARCHAR2(10),
NOMBRE VARCHAR2(10),
id_profesor varchar2(10),
CONSTRAINT PK_ASIGNATURA PRIMARY KEY (COD_ASIGNATURA),
CONSTRAINT FK_ASIGNATURA FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR(ID_PROFESOR)
);

CREATE TABLE RECIBE
(
NUM_MATRICULA NUMBER(10),
COD_ASIGNATURA VARCHAR2(10),
CURSO_ESCOLAR NUMBER(5),
CONSTRAINT PK1_RECIBE PRIMARY KEY (NUM_MATRICULA,COD_ASIGNATURA,CURSO_ESCOLAR),
CONSTRAINT FK1_RECIBE FOREIGN KEY (NUM_MATRICULA) REFERENCES ALUMNOS(NUM_MATRICULA),
CONSTRAINT FK2_RECIBE FOREIGN KEY (COD_ASIGNATURA) REFERENCES ASIGNATURA(COD_ASIGNATURA)
);





