CREATE TABLE EMPLEADO
(
CODEMP VARCHAR(10),
NIF VARCHAR(10) unique,
APELLIDOS VARCHAR(10),
DIRECCION VARCHAR(15),
TELEFONO INT(10),
FECHNAC DATE,
SALARIO INT(10)
);

CREATE TABLE CURSO
(
CODCURSO VARChaR(10),
NOMBRE VARCHAR(10),
DURACION INT(10),
COSTE INT(10)
);

CREATE TABLE EMPCAPACITADO
(
CODEMP VARCHAR(10)
);

CREATE TABLE EMPNOCAPACITADO
(
CODEMP VARCHAR(10)
);

CREATE TABLE EDICION
(
CODCURSO VARCHAR(10),
FECHAINICIO DATE,
LUGAR VARCHAR(10),
HORARIO VARCHAR(10),
PROFESOR VARCHAR(10)
);

CREATE TABLE RECIBE
(
CODEMPLEADO VARCHAR(10),
CODCURSO VARCHAR(10),
FECHAINICIO DATE
);
CREATE TABLE PRERREQUISITO
(
CURSOSOLICITADO VARCHAR(10),
CURSOPREVIO VARCHAR(10),
OBLIOGATORIO VARCHAR(5)
);


ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODEMP);

ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY (CODCURSO);

ALTER TABLE EMPCAPACITADO ADD CONSTRAINT PK_EMPCAPACITADO PRIMARY KEY (CODEMP);
ALTER TABLE EMPCAPACITADO ADD CONSTRAINT FK1_EMPCAPACITADO FOREIGN KEY (CODEMP) REFERENCES EMPLEADO (CODEMP);

ALTER TABLE EMPNOCAPACITADO ADD CONSTRAINT PK_EMPNOCAPACITADO PRIMARY KEY (CODEMP);
ALTER TABLE EMPNOCAPACITADO ADD CONSTRAINT FK1_EMPNOCAPACITADO FOREIGN KEY (CODEMP) REFERENCES EMPLEADO (CODEMP);

ALTER TABLE EDICION ADD CONSTRAINT PK_EDICION PRIMARY KEY (CODCURSO,FECHAINICIO);
ALTER TABLE EDICION ADD CONSTRAINT  FK1_EDICION FOREIGN KEY (CODCURSO) REFERENCES CURSO (CODCURSO);
ALTER TABLE EDICION ADD CONSTRAINT FK2_EDICION FOREIGN KEY (PROFESOR) REFERENCES EMPCAPACITADO (CODEMP);

ALTER TABLE RECIBE ADD CONSTRAINT PK_RECIBE PRIMARY KEY (CODEMPLEADO,CODCURSO,FECHAINICIO);
ALTER TABLE RECIBE ADD CONSTRAINT FK1_RECIBE FOREIGN KEY (CODEMPLEADO) REFERENCES EMPLEADO (CODEMP);
ALTER TABLE RECIBE ADD CONSTRAINT FK2_RECIBE FOREIGN KEY (CODCURSO,FECHAINICIO) REFERENCES EDICION (CODCURSO,FECHAINICIO);

ALTER TABLE PRERREQUISITO ADD CONSTRAINT PK_PRERREQUISITO PRIMARY KEY (CURSOSOLICITADO,CURSOPREVIO);
ALTER TABLE PRERREQUISITO ADD CONSTRAINT FK1_PRERREQUISITO FOREIGN KEY (CURSOSOLICITADO) REFERENCES CURSO (CODCURSO);
ALTER TABLE PRERREQUISITO ADD CONSTRAINT FK2_PRERREQUISITO FOREIGN KEY (CURSOPREVIO) REFERENCES CURSO (CODCURSO);

















