CREATE TABLE CLIENTE
(
CODCLIENTE VARCHAR(10),
NOMBRE VARCHAR(15),
CALLE VARCHAR(15),
NUMERO INT(10),
COMUNA VARCHAR(10),
CIUDAD VARCHAR(10)
);

CREATE TABLE TELEFONO
(
NUMERO INT(10)
);

CREATE TABLE CATEGORIA
(
IDCATEGORIA VARCHAR(15),
NOMBRE VARCHAR(15),
DESCRIPCION VARCHAR(25)
);

CREATE TABLE PROVEEDOR
(
CODPROVEEDOR VARCHAR(10),
NOMBRE VARCHAR(15),
DIRECCION VARCHAR(15),
TELEFONO INT(10),
WEB VARCHAR(15)
);

CREATE TABLE VENTA
(
IDVENTA VARCHAR(15),
MONTOTOTAL INT(10),
CODCLIENTE VARCHAR(10)
);

CREATE TABLE PRODUCTO
(
IDPRODUCTO VARCHAR(10),
NOMBRE VARCHAR(15),
PRECIO INT(10),
STOCK INT(10),
IDCATEGORIA VARCHAR(10),
IDPROVEEDOR VARCHAR(10)
);

CREATE TABLE ASOCIADO
(
CODCLIENTE VARCHAR(10),
NUMTELEFONO INT(10)
);

CREATE TABLE INCLUYE
(
IDVENTA VARCHAR(10),
IDPRODUCTO VARCHAR(10),
CANTIDAD INT(10),
PRECIOVENTA INT(10)
);



ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CODCLIENTE);

ALTER TABLE TELEFONO ADD CONSTRAINT PK_TELEFONO PRIMARY KEY (NUMERO);

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (IDCATEGORIA);

ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (CODPROVEEDOR);

ALTER TABLE VENTA ADD CONSTRAINT PK_VENTA PRIMARY KEY (IDVENTA);
ALTER TABLE VENTA ADD CONSTRAINT FK1_VENTA FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE);

ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (IDPRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK1_PRODUCTO FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (IDCATEGORIA);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK2_PRODUCTO FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR (CODPROVEEDOR);

ALTER TABLE ASOCIADO ADD CONSTRAINT PK_ASOCIADO PRIMARY KEY (CODCLIENTE,NUMTELEFONO);
ALTER TABLE ASOCIADO ADD CONSTRAINT FK1_ASOCIADO FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE);
ALTER TABLE ASOCIADO ADD CONSTRAINT FK2_ASOCIADO FOREIGN KEY (NUMTELEFONO) REFERENCES TELEFONO (NUMERO);

ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE PRIMARY KEY (IDVENTA,IDPRODUCTO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK1_INCLUYE FOREIGN KEY (IDVENTA) REFERENCES VENTA (IDVENTA);
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO);



























