CREATE TABLE PERIODISTA
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(10) NOT NULL,
DIRECCION VARCHAR2(10),
TELEFONO NUMBER(10),
ESPECIALISTA VARCHAR2(10),
CONSTRAINT PK_PERIODISTA PRIMARY KEY (DNI)
);

CREATE TABLE SUCURSAL
(
CODIGO VARCHAR2(10),
DIRECCION VARCHAR2(10),
TELEFONO NUMBER(10),
CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(10) NOT NULL,
DIRECCION VARCHAR2(10),
TELEFONO NUMBER(10),
SUCURSAL VARCHAR2(10),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);

CREATE TABLE REVISTA
(
NUM_REG NUMBER(10),
TITULO VARCHAR2(20) NOT NULL,
PERIODICIDAD VARCHAR2(20),
TIPO VARCHAR2(10),
SUCURSAL VARCHAR2(10),
CONSTRAINT PK_REVISTA PRIMARY KEY (NUM_REG),
CONSTRAINT FK1_REVISTA FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);

CREATE TABLE NUM_REVISTA
(
NUM_REG NUMBER(10),
NUMERO NUMBER(10),
NUM_PAGINAS NUMBER(10),
FECHA DATE,
CANT_VENTAS NUMBER(10),
CONSTRAINT PK_NUM_REVISTA PRIMARY KEY (NUM_REG,NUMERO),
CONSTRAINT FK1_NUM_REVISTAS FOREIGN KEY (NUM_REG) REFERENCES REVISTA(NUM_REG)
);

CREATE TABLE ESCRIBE
(
NUM_REG NUMBER(10),
DNI_PER VARCHAR2(10),
CONSTRAINT PK_ESCRIBE PRIMARY KEY (NUM_REG,DNI_PER),
CONSTRAINT FK1_ESCRIBE FOREIGN KEY (NUM_REG) REFERENCES REVISTA(NUM_REG),
CONSTRAINT FK2_ESCRIBE FOREIGN KEY (DNI_PER) REFERENCES PERIODISTA(DNI)
);


ALTER TABLE REVISTA ADD CONSTRAINT CHK_PERIODICIDAD CHECK (PERIODICIDAD IN ('SEMANAL','QUINCENAL','MENSUAL','TRIMESTRAL','ANUAL'));







