CREATE TABLE REGION 
(
COD_REGION VARCHAR2(10),
NOMBRE VARCHAR2(10),
CONSTRAINT PK_REGION PRIMARY KEY (COD_REGION)
);

CREATE TABLE PROVINCIA
(
COD_PROVINCIA VARCHAR2(10),
NOMBRE VARCHAR2(10),
COD_REGION VARCHAR2(10),
CONSTRAINT PK_PROVINCIA PRIMARY KEY (COD_PROVINCIA),
CONSTRAINT FK1_PROVINCIA FOREIGN KEY (COD_REGION) REFERENCES REGION(COD_REGION)
);

CREATE TABLE LOCALIDAD
(
COD_LOCALIDAD VARCHAR2(10),
NOMBRE VARCHAR2(10),
COD_PROVINCIA VARCHAR2(10),
CONSTRAINT PK_LOCALIDAD PRIMARY KEY (COD_LOCALIDAD),
CONSTRAINT FK1_LOCALIDAD FOREIGN KEY (COD_PROVINCIA) REFERENCES PROVINCIA(COD_PROVINCIA)
);

CREATE TABLE EMPLEADO
(
ID VARCHAR2(10),
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
FECHA_NAC DATE,
TELEFONO NUMBER(10),
SALARIO NUMBER(10),
COD_LOCALIDAD VARCHAR2(10),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD)
);