--1.Para cada titulación ordenar por coste mostrando primero las asignaturas más caras y para las asignaturas del mismo coste mostrar por orden alfabético de nombre de asignatura. 
SELECT A.NOMBRE, A.COSTEBASICO, A.IDTITULACION 
FROM ASIGNATURA A 
WHERE A.COSTEBASICO IS NOT NULL 
ORDER BY A.COSTEBASICO DESC, A.NOMBRE;

SELECT A.NOMBRE, A.COSTEBASICO, A.IDTITULACION 
FROM ASIGNATURA A 
INNER JOIN TITULACION T 
ON A.IDTITULACION = T.IDTITULACION 
ORDER BY A.COSTEBASICO DESC, A.NOMBRE;

--2.Mostrar el nombre y los apellidos de los profesores. 
SELECT P.NOMBRE, P.APELLIDO 
FROM PERSONA P 
WHERE P.DNI IN (SELECT DNI FROM PROFESOR);

SELECT P.NOMBRE, P.APELLIDO 
FROM PERSONA P 
INNER JOIN PROFESOR PR 
ON P.DNI = PR.DNI;

--3.Mostrar el nombre de las asignaturas impartidas por profesores de Sevilla. 
SELECT A.NOMBRE 
FROM ASIGNATURA A 
INNER JOIN PROFESOR PR
ON A.IDPROFESOR = PR.IDPROFESOR
INNER JOIN PERSONA P 
ON PR.DNI = P.DNI 
WHERE P.CIUDAD = 'Sevilla';

--4.Mostrar el nombre y los apellidos de los alumnos.
SELECT P.NOMBRE, P.APELLIDO 
FROM PERSONA P 
WHERE P.DNI IN (SELECT DNI FROM ALUMNO);

SELECT P.NOMBRE, P.APELLIDO 
FROM PERSONA P 
INNER JOIN ALUMNO A 
ON P.DNI = A.DNI;

--5.Mostrar el DNI, nombre y apellidos de los alumnos que viven en Sevilla. 
SELECT P.DNI , P.NOMBRE , P.APELLIDO 
FROM PERSONA p , ALUMNO a 
WHERE P.DNI = A.DNI 
AND P.CIUDAD = 'Sevilla';

SELECT A.DNI, P.NOMBRE, P.APELLIDO 
FROM ALUMNO A 
INNER JOIN PERSONA P 
ON A.DNI = P.DNI 
WHERE P.CIUDAD = 'Sevilla';

--6.Mostrar el DNI, nombre y apellidos de los alumnos matriculados en la asignatura "Seguridad Vial". 
SELECT A.DNI, P.NOMBRE, P.APELLIDO 
FROM ALUMNO A, PERSONA P, ALUMNO_ASIGNATURA AA, ASIGNATURA ASG
WHERE A.DNI = P.DNI
AND A.IDALUMNO = AA.IDALUMNO
AND AA.IDASIGNATURA = ASG.IDASIGNATURA
AND ASG.NOMBRE = 'Seguridad Vial';

SELECT A.DNI, P.NOMBRE, P.APELLIDO 
FROM ALUMNO A
INNER JOIN PERSONA P ON A.DNI = P.DNI
INNER JOIN ALUMNO_ASIGNATURA AA ON A.IDALUMNO = AA.IDALUMNO
INNER JOIN ASIGNATURA ASG ON AA.IDASIGNATURA = ASG.IDASIGNATURA
WHERE ASG.NOMBRE = 'Seguridad Vial';

--7.Mostrar el Id de las titulaciones en las que está matriculado el alumno con DNI 20202020A. 
--Un alumno está matriculado en una titulación si está matriculado en una asignatura de la titulación.
SELECT DISTINCT A.IDTITULACION
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL
WHERE A.IDASIGNATURA = AA.IDASIGNATURA
AND AA.IDALUMNO = AL.IDALUMNO
AND AL.DNI = '20202020A';

SELECT DISTINCT A.IDTITULACION
FROM ASIGNATURA A
INNER JOIN ALUMNO_ASIGNATURA AA ON A.IDASIGNATURA = AA.IDASIGNATURA
INNER JOIN ALUMNO AL ON AA.IDALUMNO = AL.IDALUMNO
WHERE AL.DNI = '20202020A';

--8.Obtener el nombre de las asignaturas en las que está matriculada Rosa Garcia.
SELECT ASG.NOMBRE
FROM ASIGNATURA ASG, ALUMNO_ASIGNATURA AA, ALUMNO A, PERSONA P
WHERE ASG.IDASIGNATURA = AA.IDASIGNATURA
AND AA.IDALUMNO = A.IDALUMNO
AND A.DNI = P.DNI
AND P.NOMBRE = 'Rosa'
AND P.APELLIDO = 'Garcia';

SELECT ASG.NOMBRE
FROM ASIGNATURA ASG
INNER JOIN ALUMNO_ASIGNATURA AA ON ASG.IDASIGNATURA = AA.IDASIGNATURA
INNER JOIN ALUMNO A ON AA.IDALUMNO = A.IDALUMNO
INNER JOIN PERSONA P ON A.DNI = P.DNI
WHERE P.NOMBRE = 'Rosa' AND P.APELLIDO = 'Garcia';

--9.Obtener el DNI de los alumnos a los que le imparte clase el profesor Jorge Saenz. 
SELECT DISTINCT A.DNI
FROM ALUMNO A, ALUMNO_ASIGNATURA AA, ASIGNATURA ASG, PROFESOR PR, PERSONA P
WHERE A.IDALUMNO = AA.IDALUMNO
AND AA.IDASIGNATURA = ASG.IDASIGNATURA
AND ASG.IDPROFESOR = PR.IDPROFESOR
AND PR.DNI = P.DNI
AND P.NOMBRE = 'Jorge'
AND P.APELLIDO = 'Saenz';

SELECT DISTINCT A.DNI
FROM ALUMNO A
INNER JOIN ALUMNO_ASIGNATURA AA ON A.IDALUMNO = AA.IDALUMNO
INNER JOIN ASIGNATURA ASG ON AA.IDASIGNATURA = ASG.IDASIGNATURA
INNER JOIN PROFESOR PR ON ASG.IDPROFESOR = PR.IDPROFESOR
INNER JOIN PERSONA P ON PR.DNI = P.DNI
WHERE P.NOMBRE = 'Jorge' AND P.APELLIDO = 'Saenz';

--10.Obtener el DNI, nombre y apellido de los alumnos a los que imparte clase el profesor Jorge Sáenz. 
SELECT distinct p2.DNI,p2.NOMBRE,p2.APELLIDO 
FROM ASIGNATURA t 
JOIN ALUMNO_ASIGNATURA aa 
ON aa.IDASIGNATURA = t.IDASIGNATURA 
JOIN ALUMNO a 
ON a.IDALUMNO = aa.IDALUMNO
JOIN persona p2
ON p2.DNI = a.DNI 
JOIN PROFESOR pr
ON pr.IDPROFESOR = t.IDPROFESOR 
JOIN PERSONA p 
ON p.DNI = pr.DNI
WHERE p.NOMBRE = 'Jorge'
AND p.APELLIDO ='Saenz';

--11.Mostrar el nombre de las titulaciones que tengan al menos una asignatura de 4 créditos. 
SELECT DISTINCT T.NOMBRE 
FROM TITULACION T, ASIGNATURA A
WHERE A.IDTITULACION = T.IDTITULACION
AND A.CREDITOS >= 4;

SELECT DISTINCT T.NOMBRE 
FROM TITULACION T
INNER JOIN ASIGNATURA A ON A.IDTITULACION = T.IDTITULACION
WHERE A.CREDITOS >= 4;

--12.Mostrar el nombre y los créditos de las asignaturas del primer cuatrimestre junto con el nombre de la titulación a la que pertenecen. 
SELECT A.NOMBRE, A.CREDITOS, T.NOMBRE 
FROM ASIGNATURA A, TITULACION T
WHERE A.IDTITULACION = T.IDTITULACION
AND A.CUATRIMESTRE = 1;

SELECT A.NOMBRE, A.CREDITOS, T.NOMBRE 
FROM ASIGNATURA A
INNER JOIN TITULACION T ON A.IDTITULACION = T.IDTITULACION
WHERE A.CUATRIMESTRE = 1;

--13.Mostrar el nombre y el coste básico de las asignaturas de más de 4,5 créditos junto con el nombre de las personas matriculadas
SELECT A.NOMBRE, A.COSTEBASICO, P.NOMBRE, P.APELLIDO 
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL, PERSONA P
WHERE A.IDASIGNATURA = AA.IDASIGNATURA
AND AA.IDALUMNO = AL.IDALUMNO
AND AL.DNI = P.DNI
AND A.CREDITOS > 4.5;

SELECT A.NOMBRE, A.COSTEBASICO, P.NOMBRE, P.APELLIDO 
FROM ASIGNATURA A
INNER JOIN ALUMNO_ASIGNATURA AA ON A.IDASIGNATURA = AA.IDASIGNATURA
INNER JOIN ALUMNO AL ON AA.IDALUMNO = AL.IDALUMNO
INNER JOIN PERSONA P ON AL.DNI = P.DNI
WHERE A.CREDITOS > 4.5;

--14.Mostrar el nombre de los profesores que imparten asignaturas con coste entre 25 y 35 euros, ambos incluidos
SELECT P.NOMBRE
FROM PERSONA p , PROFESOR pp , ASIGNATURA a 
WHERE P.DNI = PP.DNI 
AND PP.IDPROFESOR = A.IDPROFESOR 
AND A.COSTEBASICO BETWEEN 25 AND 35;

SELECT P.NOMBRE
FROM PERSONA P
INNER JOIN PROFESOR PP ON P.DNI = PP.DNI
INNER JOIN ASIGNATURA A ON PP.IDPROFESOR = A.IDPROFESOR
WHERE A.COSTEBASICO BETWEEN 25 AND 35;

--15.Mostrar el nombre de los alumnos matriculados en la asignatura '150212' ó en la '130113' ó en ambas.
SELECT P.NOMBRE, P.APELLIDO 
FROM ALUMNO A, ALUMNO_ASIGNATURA AA, ASIGNATURA ASG, PERSONA P
WHERE A.IDALUMNO = AA.IDALUMNO
AND AA.IDASIGNATURA = ASG.IDASIGNATURA
AND ASG.IDASIGNATURA IN ('150212', '130113')
AND A.DNI = P.DNI;

SELECT P.NOMBRE, P.APELLIDO 
FROM ALUMNO A
INNER JOIN ALUMNO_ASIGNATURA AA ON A.IDALUMNO = AA.IDALUMNO
INNER JOIN ASIGNATURA ASG ON AA.IDASIGNATURA = ASG.IDASIGNATURA
INNER JOIN PERSONA P ON A.DNI = P.DNI
WHERE ASG.IDASIGNATURA IN ('150212', '130113');

--16.Mostrar el nombre de las asignaturas del 2º cuatrimestre que no sean de 6 créditos, junto con el nombre de la titulación a la que pertenece.
SELECT A.NOMBRE, T.NOMBRE 
FROM ASIGNATURA A, TITULACION T
WHERE A.IDTITULACION = T.IDTITULACION
AND A.CUATRIMESTRE = 2
AND A.CREDITOS <> 6;

SELECT A.NOMBRE, T.NOMBRE 
FROM ASIGNATURA A
INNER JOIN TITULACION T ON A.IDTITULACION = T.IDTITULACION
WHERE A.CUATRIMESTRE  = 2 AND A.CREDITOS <> 6;

--17.Mostrar el nombre y el número de horas de todas las asignaturas. (1cred.=10 horas) junto con el dni de los alumnos que están matriculados.
SELECT A.NOMBRE, (A.CREDITOS * 10) AS HORAS, P.DNI 
FROM ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL, PERSONA P
WHERE A.IDASIGNATURA = AA.IDASIGNATURA
AND AA.IDALUMNO = AL.IDALUMNO
AND AL.DNI = P.DNI;

SELECT A.NOMBRE, (A.CREDITOS * 10) AS HORAS, P.DNI 
FROM ASIGNATURA A
INNER JOIN ALUMNO_ASIGNATURA AA ON A.IDASIGNATURA = AA.IDASIGNATURA
INNER JOIN ALUMNO AL ON AA.IDALUMNO = AL.IDALUMNO
INNER JOIN PERSONA P ON AL.DNI = P.DNI;

--18.Mostrar el nombre de todas las mujeres que viven en “Sevilla” y que estén matriculados de alguna asignatura
SELECT P.NOMBRE 
FROM PERSONA P, ALUMNO A, ALUMNO_ASIGNATURA AA
WHERE A.DNI = P.DNI
AND A.IDALUMNO = AA.IDALUMNO
AND P.CIUDAD = 'Sevilla'
AND P.VARON = 0;

SELECT P.NOMBRE 
FROM PERSONA P
INNER JOIN ALUMNO A ON P.DNI = A.DNI
INNER JOIN ALUMNO_ASIGNATURA AA ON A.IDALUMNO = AA.IDALUMNO
WHERE P.CIUDAD = 'Sevilla' AND P.VARON = 0;
SELECT * FROM PERSONA;
--19.Mostrar el nombre de la asignatura de primero y que lo imparta el profesor con identificador p101.
SELECT A.NOMBRE 
FROM ASIGNATURA A, PROFESOR P
WHERE A.IDPROFESOR = P.IDPROFESOR
AND A.CURSO = 1
AND P.IDPROFESOR = 'p101';

SELECT A.NOMBRE 
FROM ASIGNATURA A
INNER JOIN PROFESOR P ON A.IDPROFESOR = P.IDPROFESOR
WHERE A.CURSO = 1 AND P.IDPROFESOR = 'p101';

--20.Mostrar el nombre de los alumnos que se ha matriculado tres o más veces en alguna asignatura.
SELECT P.NOMBRE 
FROM PERSONA p , ALUMNO a  ,ALUMNO_ASIGNATURA aa 
WHERE P.DNI = A.DNI 
AND A.IDALUMNO = AA.IDALUMNO 
AND AA.NUMEROMATRICULA >= 3;

SELECT P.NOMBRE 
FROM PERSONA p 
INNER JOIN ALUMNO a ON P.DNI = A.DNI 
INNER JOIN ALUMNO_ASIGNATURA aa ON A.IDALUMNO = AA.IDALUMNO 
WHERE AA.NUMEROMATRICULA >= 3;












