CREATE TABLE BARCOS (
    MATRICULA VARCHAR2(10),
    NOMBRE VARCHAR2(20),
    CLASE VARCHAR2(20),
    ARMADOR VARCHAR2(20),
    CAPACIDAD NUMBER(15),
    NACIONALIDAD VARCHAR2(20)
);

CREATE TABLE CALADERO (
    CODIGO VARCHAR2(15),
    NOMBRE VARCHAR2(15),
    UBICACION VARCHAR2(20),
    ESPECIE_PRINCIPAL VARCHAR2(15)
);

CREATE TABLE ESPECIE (
    CODIGO VARCHAR2(15),
    NOMBRE VARCHAR2(20),
    TIPO VARCHAR2(20),
    CUPOPORBARCO NUMBER(10),
    CALADERO_PRINCIPAL VARCHAR2(15)
);

CREATE TABLE LOTES (
    CODIGO VARCHAR2(15),
    MATRICULA VARCHAR2(20),
    NUMKILOS NUMBER(10),
    PRECIOPORKILOSALIDA NUMBER(10),
    PRECIOPORKILOADJUDICADO NUMBER(10),
    FECHAVENTA DATE NOT NULL,
    COD_ESPECIE VARCHAR2(15)
);

CREATE TABLE FECHAS_CAPTURAS_PERMITIDAS (
    COD_ESPECIE VARCHAR2(15),
    COD_CALADERO VARCHAR2(15),
    FECHA_INICIAL DATE,
    FECHA_FINAL DATE
);

ALTER TABLE BARCOS ADD CONSTRAINT PK_BARCOS PRIMARY KEY (MATRICULA);

ALTER TABLE CALADERO ADD CONSTRAINT PK_CALADERO PRIMARY KEY (CODIGO);

ALTER TABLE ESPECIE ADD CONSTRAINT PK_ESPECIE PRIMARY KEY (CODIGO);

ALTER TABLE LOTES ADD CONSTRAINT PK_LOTES PRIMARY KEY (CODIGO);

ALTER TABLE FECHAS_CAPTURAS_PERMITIDAS ADD CONSTRAINT PK_FECHAS_CAPTURAS PRIMARY KEY (COD_ESPECIE, COD_CALADERO);

ALTER TABLE CALADERO ADD CONSTRAINT FK_CALADERO_ESPECIE FOREIGN KEY (ESPECIE_PRINCIPAL) REFERENCES ESPECIE(CODIGO) ON DELETE SET NULL;

ALTER TABLE ESPECIE ADD CONSTRAINT FK_ESPECIE_CALADERO FOREIGN KEY (CALADERO_PRINCIPAL) REFERENCES CALADERO(CODIGO) ON DELETE SET NULL;

ALTER TABLE LOTES ADD CONSTRAINT FK_LOTES_BARCOS FOREIGN KEY (MATRICULA) REFERENCES BARCOS(MATRICULA) ON DELETE CASCADE;

ALTER TABLE LOTES ADD CONSTRAINT FK_LOTES_ESPECIE FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIE(CODIGO) ON DELETE CASCADE;

ALTER TABLE FECHAS_CAPTURAS_PERMITIDAS ADD CONSTRAINT FK_FECHAS_ESPECIE FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIE(CODIGO);

ALTER TABLE FECHAS_CAPTURAS_PERMITIDAS ADD CONSTRAINT FK_FECHAS_CALADERO FOREIGN KEY (COD_CALADERO) REFERENCES CALADERO(CODIGO);




ALTER TABLE BARCOS ADD CONSTRAINT CHK_MATRICULA CHECK (REGEXP_LIKE(MATRICULA, '^[A-Z]{2}-[0-9]{4}'));

ALTER TABLE LOTES ADD CONSTRAINT CHK_PRECIOKILO CHECK (PRECIOPORKILOADJUDICADO > PRECIOPORKILOSALIDA);

ALTER TABLE LOTES ADD CONSTRAINT CHK_NUMKILOS CHECK (NUMKILOS > 0);

ALTER TABLE LOTES ADD CONSTRAINT CHK_PRECIOPORKILOSALIDA CHECK (PRECIOPORKILOSALIDA >0);

ALTER TABLE LOTES ADD CONSTRAINT CHK_PRECIOPORKILOADJUDICADO CHECK(PRECIOPORKILOADJUDICADO > 0);

ALTER TABLE CALADERO ADD CONSTRAINT CHK_CALADERO_MAYUSCULAS CHECK (NOMBRE = UPPER(NOMBRE) AND UBICACION = UPPER(UBICACION));

ALTER TABLE FECHAS_CAPTURAS_PERMITIDAS ADD CONSTRAINT CHK_FECHAS_CAPTURA_RESTRINGIDAS
CHECK ((FECHA_INICIAL < TO_DATE('02-02-2024', 'DD-MM-YYYY') OR  FECHA_FINAL > TO_DATE('02-02-2024', 'DD-MM-YYYY')) 
OR  (FECHA_INICIAL > TO_DATE('28-03-2024', 'DD-MM-YYYY') OR FECHA_FINAL > TO_DATE('28-03-2024', 'DD-MM-YYYY')));

INSERT INTO FECHAS_CAPTURAS_PERMITIDAS (COD_ESPECIE,COD_CALADERO,FECHA_INICIAL,FECHA_FINAL) VALUES ('SS','SD',TO_DATE('08-02-2024','DD-MM-YYYY'),TO_DATE('02-03-2024','DD-MM-YYYY'));

ALTER TABLE CALADERO ADD NOMBRE_CIENTIFICO VARCHAR2(15);

INSERT INTO CALADERO (CODIGO,NOMBRE,UBICACION) VALUES ('EEE','JUAN','SEVILLA');

/*BARCOS*/

INSERT INTO BARCOS (MATRICULA, NOMBRE, CLASE, ARMADOR, CAPACIDAD, NACIONALIDAD)
VALUES ('B001', 'Barco Pesquero A', 'Pesquero', 'Armador A', 500, 'España');

INSERT INTO BARCOS (MATRICULA, NOMBRE, CLASE, ARMADOR, CAPACIDAD, NACIONALIDAD)
VALUES ('B002', 'Barco Pesquero B', 'Pesquero', 'Armador B', 700, 'Francia');


/*CALDERO*/

INSERT INTO CALADERO (CODIGO, NOMBRE, UBICACION, ESPECIE_PRINCIPAL, NOMBRE_CIENTIFICO)
VALUES ('C001', 'Caladero Norte', 'Zona Norte', 'E001', 'Gadus morhua');

INSERT INTO CALADERO (CODIGO, NOMBRE, UBICACION, ESPECIE_PRINCIPAL, NOMBRE_CIENTIFICO)
VALUES ('C002', 'SUR', 'SUR', 'E002', 'Thunnus thynnus');

/*ESPECIE*/

INSERT INTO ESPECIE (CODIGO, NOMBRE, TIPO, CUPOPORBARCO, CALADERO_PRINCIPAL)
VALUES ('E001', 'Merluza', 'Pescado', 500, 'C001');

INSERT INTO ESPECIE (CODIGO, NOMBRE, TIPO, CUPOPORBARCO, CALADERO_PRINCIPAL)
VALUES ('E002', 'Atún', 'Pescado', 700, 'C002');

/*LOTES*/

INSERT INTO LOTES (CODIGO, MATRICULA, NUMKILOS, PRECIOPORKILOSALIDA, PRECIOPORKILOADJUDICADO, FECHAVENTA, COD_ESPECIE)
VALUES ('L001', 'B001', 1000, 5, 6, TO_DATE('2024-06-01', 'YYYY-MM-DD'), 'E001'); 

INSERT INTO LOTES (CODIGO, MATRICULA, NUMKILOS, PRECIOPORKILOSALIDA, PRECIOPORKILOADJUDICADO, FECHAVENTA, COD_ESPECIE)
VALUES ('L002', 'B002', 1500, 8, 9, TO_DATE('2024-07-01', 'YYYY-MM-DD'), 'E002');

/*FECHA_CAPTURPERMITIDAS*/

INSERT INTO FECHAS_CAPTURAS_PERMITIDAS (COD_ESPECIE, COD_CALADERO, FECHA_INICIAL, FECHA_FINAL)
VALUES ('E001', 'C001', TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD')); 

INSERT INTO FECHAS_CAPTURAS_PERMITIDAS (COD_ESPECIE, COD_CALADERO, FECHA_INICIAL, FECHA_FINAL)
VALUES ('E002', 'C002', TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-11-30', 'YYYY-MM-DD'));  


ALTER TABLE BARCOS DROP COLUMN ARMADOR;

/*ELIMINAR TABLAS*/

DROP TABLE FECHAS_CAPTURAS_PERMITIDAS CASCADE CONSTRAINTS;
DROP TABLE LOTES CASCADE CONSTRAINTS;
DROP TABLE ESPECIE CASCADE CONSTRAINTS;
DROP TABLE CALADERO CASCADE CONSTRAINTS;
DROP TABLE BARCOS CASCADE CONSTRAINTS;







