CREATE TABLE OFICINA
(
CODIGO_OFICINA VARCHAR2(10),
CIUDAD VARCHAR2(30),
PAIS VARCHAR2(30),
REGION VARCHAR2(50),
CODIGO_POSTAL VARCHAR2(10),
TELEFONO VARCHAR2(20),
LINEA_DIRECCION1 VARCHAR2(50),
LINEA_DIRECCION2 VARCHAR2(50),
CONSTRAINT PK_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);

CREATE TABLE EMPLEADO
(
CODIGO_EMPLEADO NUMBER(11),
NOMBRE VARCHAR2(50),
APELLIDO1 VARCHAR2(50),
APELLIDO2 VARCHAR2(50),
EXTENSION VARCHAR2(10),
EMAIL VARCHAR2(100),
CODIGO_OFICINA VARCHAR2(10),
CODIGO_JEFE NUMBER(11),
PUESTO VARCHAR2(50),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA),
CONSTRAINT FK2_EMPLEADO FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE CLIENTE
(
CODIGO_CLIENTE NUMBER(11),
NOMBRE_CLIENTE VARCHAR2(50),
NOMBRE_CONTACTO VARCHAR2(30),
APELLIDO_CONTACTO VARCHAR2(30),
TELEFONO VARCHAR2(15),
FAX VARCHAR2(15),
LINEA_DIRECCION1 VARCHAR2(50),
LINEA_DIRECCION2 VARCHAR2(50),
CIUDAD VARCHAR2(50),
REGION VARCHAR2(50),
PAIS VARCHAR2(50),
CODIGO_POSTAL VARCHAR2(10),
CODIGO_EMPLEADO_REP_VENTAS NUMBER(11),
LIMITE_CREDITO NUMBER(15,2),
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO_CLIENTE),
CONSTRAINT FK_CLIENTE FOREIGN KEY (CODIGO_EMPLEADO_REP_VENTAS) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE PAGO
(
CODIGO_CLIENTE NUMBER(11),
FORMA_PAGO VARCHAR2(40),
ID_TRANSACCION VARCHAR2(50),
FECHA_PAGO DATE,
TOTAL NUMBER(15,2),
CONSTRAINT PK_PAGO PRIMARY KEY (ID_TRANSACCION),
CONSTRAINT FK_PAGO FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE PEDIDO
(
CODIGO_PEDIDO NUMBER(11),
FECHA_PEDIDO DATE,
FECHA_ESPERADA DATE,
FECHA_ENTREGA DATE,
ESTADO VARCHAR2(15),
COMENTARIOS VARCHAR2(10),
CODIGO_CLIENTE NUMBER(11),
CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGO_PEDIDO),
CONSTRAINT FK_PEDIDO FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE GAMA_PRODUCTO
(
GAMA VARCHAR(50),
DESCRIPCION VARCHAR2(100),
DESCRIPCION_HTML VARCHAR2(100),
IMAGEN VARCHAR2(256),
CONSTRAINT PK_GAMA_PRODUCTO PRIMARY KEY (GAMA)
);

CREATE TABLE PRODUCTO
(
CODIGO_PRODUCTO VARCHAR2(15),
NOMBRE VARCHAR2(70) UNIQUE,
GAMA VARCHAR2(50),
DIMENSIONES VARCHAR2(25),
PROVEEDOR VARCHAR2(50),
DESCRIPCION VARCHAR2(100),
CANTIDAD_EN_ESTOCK NUMBER(6),
PRECIO_VENTA NUMBER(15,2),
PRECIO_PROVEEDOR NUMBER(15,2),
CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO),
CONSTRAINT FK_PRODUCTO FOREIGN KEY (GAMA) REFERENCES GAMA_PRODUCTO(GAMA)
);

CREATE TABLE DETALLE_PEDIDO
(
CODIGO_PEDIDO NUMBER(11),
CODIGO_PRODUCTO VARCHAR2(15),
CANTIDAD NUMBER(11),
PRECIO_UNIDAD NUMBER(15,2),
NUMERO_LINEA NUMBER(6),
CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (CODIGO_PEDIDO,CODIGO_PRODUCTO),
CONSTRAINT FK1_DETALLE_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO_PEDIDO),
CONSTRAINT FK2_DESTALLE_PEDIDO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO)
);