/*alter session set "_oracle_script"=true;  
create user PRUEBAROLDANDURANJAVIER identified by PRUEBAROLDANDURANJAVIER;
GRANT CONNECT, RESOURCE, DBA TO PRUEBAROLDANDURANJAVIER;*/

/*CREACION DE TABLAS*/

CREATE TABLE COMUNIDAD_AUTONOMA
(
	COD_CA VARCHAR2(10),
	NOMBRE VARCHAR2(25),
	ORG_RESPONSABLE VARCHAR2(25),
	CONSTRAINT PK_COMUNIDAD_AUTONOMO PRIMARY KEY (COD_CA)
);

CREATE TABLE PARQUE_NATURAL 
(
	COD_PQN VARCHAR2(10),
	NOMBRE VARCHAR2(25),
	FECHA_DECLARACION DATE,
	CONSTRAINT PK_PARQUE_NATURAL PRIMARY KEY (COD_PQN)
);

CREATE TABLE ENTRADA 
(
	COD_ENTRADA VARCHAR2(10),
	COD_PQN VARCHAR2(10),
	CONSTRAINT PK_ENTRADA PRIMARY KEY (COD_ENTRADA),
	CONSTRAINT FK_ENTRADA FOREIGN KEY (COD_PQN) REFERENCES PARQUE_NATURAL (COD_PQN)
);

CREATE TABLE CA_PN
(
	SUPERFICIE NUMBER(10),
	COD_PQN VARCHAR2(10),
	COD_CA VARCHAR2(10),
	CONSTRAINT PK_CA_PN PRIMARY KEY (COD_PQN,COD_CA),
	CONSTRAINT FK1_CA_PN FOREIGN KEY (COD_PQN) REFERENCES PARQUE_NATURAL(COD_PQN),
	CONSTRAINT FK2_CA_PN FOREIGN KEY (COD_CA) REFERENCES COMUNIDAD_AUTONOMA(COD_CA)
);

CREATE TABLE AREA 
(
	NOMBRE VARCHAR2(25),
	EXTENSION NUMBER(10),
	COD_PQN VARCHAR2(10),
	CONSTRAINT PK_AREA PRIMARY KEY (NOMBRE),
	CONSTRAINT FK_AREA FOREIGN KEY (COD_PQN) REFERENCES PARQUE_NATURAL (COD_PQN)
);

CREATE TABLE PERSONAL 
(
	DNI VARCHAR2(10),
	NSS NUMBER(10),
	NOMBRE VARCHAR2(25),
	DIRECCION VARCHAR2(50),
	TLFDOMICILIO NUMBER(10),
	TLFMOVIL NUMBER(10),
	SUELDO NUMBER(10),
	COD_PQN VARCHAR2(10),
	CONSTRAINT PK_PERSONAL PRIMARY KEY (DNI),
	CONSTRAINT FK_PERSONAL FOREIGN KEY (COD_PQN) REFERENCES PARQUE_NATURAL (COD_PQN)
);

CREATE TABLE INVESTIGADOR 
(
	DNI VARCHAR2(10),
	TIPO VARCHAR2(25),
	TITULACION VARCHAR2(25),
	CONSTRAINT PK_INVESTIGADOR PRIMARY KEY (DNI),
	CONSTRAINT FK_INVESTIGADOR FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)
);

CREATE TABLE CONSERVADOR 
(
	DNI VARCHAR2(10),
	TIPO VARCHAR2(25),
	TAREA VARCHAR2(25),
	NOMBRE_AREA VARCHAR2(25),
	CONSTRAINT PK_CONSERVADOR PRIMARY KEY (DNI),
	CONSTRAINT FK1_CONSERVADOR FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI),
	CONSTRAINT FK2_CONSERVADOR FOREIGN KEY (NOMBRE_AREA) REFERENCES AREA (NOMBRE)
);

CREATE TABLE GESTOR 
(
	DNI VARCHAR2(10),
	TIPO VARCHAR2(25),
	COD_ENTRADA VARCHAR2(10),
	CONSTRAINT PK_GESTOR PRIMARY KEY (DNI),
	CONSTRAINT FK1_GESTOR FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI),
	CONSTRAINT FK2_GESTOR FOREIGN KEY (COD_ENTRADA) REFERENCES ENTRADA (COD_ENTRADA)
);

CREATE TABLE VIGILANTE 
(
	DNI VARCHAR2(10),
	TIPO VARCHAR2(25),
	NOMBRE_AREA VARCHAR2(25),
	CONSTRAINT PK_VIGILANTE PRIMARY KEY (DNI),
	CONSTRAINT FK1_VIGILANTE FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI),
	CONSTRAINT FK2_VIGILANTE FOREIGN KEY (NOMBRE_AREA) REFERENCES AREA (NOMBRE)
);

CREATE TABLE VEHICULO 
(
	MATRICULA VARCHAR2(10),
	TIPO VARCHAR2(10),
	DNI_VIGILANTE VARCHAR2(10),
	CONSTRAINT PK_VEHICULO PRIMARY KEY (MATRICULA),
	CONSTRAINT FK_VEHICULO FOREIGN KEY (DNI_VIGILANTE) REFERENCES VIGILANTE (DNI)
);

CREATE TABLE PROYECTO
(
	COD_PROY VARCHAR2(10),
	PRESUPUESTO NUMBER(10),
	FECHAINICIO DATE,
	FECHAFIN DATE,
	CONSTRAINT PK_PROYECTO PRIMARY KEY (COD_PROY)
);

CREATE TABLE I_P
(
	DNI_INVESTIGADOR VARCHAR2(10),
	COD_PROY VARCHAR2(10),
	CONSTRAINT PK_IP PRIMARY KEY (DNI_INVESTIGADOR,COD_PROY),
	CONSTRAINT FK1_IP FOREIGN KEY (DNI_INVESTIGADOR) REFERENCES INVESTIGADOR (DNI),
	CONSTRAINT FK2_IP FOREIGN KEY (COD_PROY) REFERENCES PROYECTO (COD_PROY)
);

CREATE TABLE ESPECIE
(
	COD_ESPE VARCHAR2(10),
	NOMBRECIENTIFICO VARCHAR2(25),
	NOMBREVULGAR VARCHAR2(25),
	CONSTRAINT PK_ESPECIE PRIMARY KEY (COD_ESPE)
);

CREATE TABLE P_E
(
	COD_PROY VARCHAR2(10),
	COD_ESPE VARCHAR2(10),
	CONSTRAINT PK_PE PRIMARY KEY (COD_PROY,COD_ESPE),
	CONSTRAINT FK1_PE FOREIGN KEY (COD_PROY) REFERENCES PROYECTO (COD_PROY),
	CONSTRAINT FK2_PE FOREIGN KEY (COD_ESPE) REFERENCES ESPECIE (COD_ESPE)
);


CREATE TABLE E_A 
(
	COD_ESPE VARCHAR2(10),
	NOMBRE_AREA VARCHAR2(25),
	CONSTRAINT PK_EA PRIMARY KEY (COD_ESPE,NOMBRE_AREA),
	CONSTRAINT FK1_EA FOREIGN KEY (COD_ESPE) REFERENCES ESPECIE (COD_ESPE),
	CONSTRAINT FK2_EA FOREIGN KEY (NOMBRE_AREA) REFERENCES AREA (NOMBRE)
);

CREATE TABLE ANIMAL
(
	COD_ESPE VARCHAR2(10),
	ALIMENTACION VARCHAR2(10),
	PERIODOCELO DATE,
	TIPO VARCHAR2(10),
	CONSTRAINT PK_ANIMAL PRIMARY KEY (COD_ESPE),
	CONSTRAINT FK1_ANIMAL FOREIGN KEY (COD_ESPE) REFERENCES ESPECIE (COD_ESPE)
);

CREATE TABLE A_A 
(
	COD_ESPE VARCHAR2(10),
	CONSTRAINT PK_AA PRIMARY KEY (COD_ESPE),
	CONSTRAINT FK_AA FOREIGN KEY (COD_ESPE) REFERENCES ANIMAL (COD_ESPE)
);

CREATE TABLE VEGETAL 
(
	COD_ESPE VARCHAR2(10),
	FLORACION VARCHAR2(10),
	PERIODOFLORACION DATE,
	CONSTRAINT PK_VEGETAL PRIMARY KEY (COD_ESPE),
	CONSTRAINT FK1_VEGETAL FOREIGN KEY (COD_ESPE) REFERENCES ESPECIE (COD_ESPE)
);

CREATE TABLE A_V
(
	COD_ESPE VARCHAR2(10),
	CONSTRAINT PK_AV PRIMARY KEY (COD_ESPE),
	CONSTRAINT FK1_AV FOREIGN KEY (COD_ESPE) REFERENCES VEGETAL (COD_ESPE),
	CONSTRAINT FK2_AV FOREIGN KEY (COD_ESPE) REFERENCES ANIMAL (COD_ESPE)
);

CREATE TABLE MINERAL 
(
	COD_ESPE VARCHAR2(10),
	TIPO VARCHAR2(10),
	CONSTRAINT PK_MINERAL PRIMARY KEY (COD_ESPE),
	CONSTRAINT FK_MINERAL FOREIGN KEY (COD_ESPE) REFERENCES ESPECIE (COD_ESPE)
);

CREATE TABLE VISITANTE
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(25),
	DOMICILIO VARCHAR2(25),
	PROFESION VARCHAR2(25),
	CONSTRAINT PK_VISITANTE PRIMARY KEY (DNI)
);

CREATE TABLE ALOJAMIENTO 
(
	COD_ALOJAMIENTO VARCHAR2(10),
	COD_PQN VARCHAR2(10),
	CATEGORIA VARCHAR2(25),
	CAPACIDAD NUMBER(10),
	CONSTRAINT PK_ALOJAMIENTO PRIMARY KEY (COD_ALOJAMIENTO),
	CONSTRAINT FK_ALOJAMIENTO FOREIGN KEY (COD_PQN) REFERENCES PARQUE_NATURAL (COD_PQN)
);

CREATE TABLE A_V_I
(
	COD_ALOJAMIENTO VARCHAR2(10),
	DNI_VISITANTE VARCHAR2(10),
	FECHAINICIO DATE,
	FECHAFIN DATE,
	CONSTRAINT PK_AVI PRIMARY KEY (COD_ALOJAMIENTO,DNI_VISITANTE),
	CONSTRAINT FK1_AVI FOREIGN KEY (COD_ALOJAMIENTO) REFERENCES ALOJAMIENTO (COD_ALOJAMIENTO),
	CONSTRAINT FK2_AVI FOREIGN KEY (DNI_VISITANTE) REFERENCES VISITANTE (DNI)
);

CREATE TABLE EXCURSION 
(
	COD_EXCURSION VARCHAR2(10),
	COD_ALOJAMIENTO VARCHAR2(10),
	FECHA DATE,
	HORA DATE,
	PIE VARCHAR2(5),
	CONSTRAINT PK_EXCURSION PRIMARY KEY (COD_EXCURSION),
	CONSTRAINT FK_EXCURSION FOREIGN KEY (COD_ALOJAMIENTO) REFERENCES ALOJAMIENTO (COD_ALOJAMIENTO)
);

CREATE TABLE V_E 
(
	DNI_VISITANTE VARCHAR2(10),
	COD_EXCURSION VARCHAR2(10),
	CONSTRAINT PK_VE PRIMARY KEY (DNI_VISITANTE,COD_EXCURSION),
	CONSTRAINT FK1_VE FOREIGN KEY (DNI_VISITANTE) REFERENCES VISITANTE (DNI),
	CONSTRAINT FK2_VE FOREIGN KEY (COD_EXCURSION) REFERENCES EXCURSION (COD_EXCURSION)
);




/*EJERCICIO2*/




/*EJERCICIO3*/
--1
INSERT INTO PROYECTO  (COD_PROY,PRESUPUESTO,FECHAINICIO)
VALUES ('PRO1',20500,SYSDATE);

INSERT INTO PERSONAL (DNI)
VALUES ('12345678M');

INSERT INTO INVESTIGADOR (DNI,TIPO)
VALUES ('12345678M','Meteorologo');

INSERT INTO I_P (COD_PROY,DNI_INVESTIGADOR)
VALUES ('PRO1','12345678M');


INSERT INTO ESPECIE (COD_ESPE,NOMBRECIENTIFICO)
VALUES ('CL1','Canis lupus');

INSERT INTO ANIMAL (COD_ESPE,ALIMENTACION)
VALUES ('CL1','hervivoro');

INSERT INTO P_E (COD_ESPE,COD_PROY)
VALUES ('CL1','PRO1');

--2
UPDATE ANIMAL 
SET ALIMENTACION = 'carnivoro'
WHERE COD_ESPE = 'CL1';

--3
DELETE FROM EXCURSION 
WHERE FECHA < (TO_DATE('01-01-2000','DD-MM-YYYY'));

--4
/*Para persistir los datos antes realizados si no tenemos el autocommit activado, deberiamos realizar un commit manual, para ello se escribe la sentencia COMMIT;*/









