--Consultas


--1
SELECT  A.NOMBRE, A.APELLIDOS, A.TELF NUMERO_TELEFONO
FROM AFILIADOS a 
WHERE UPPER(A.SEXO) = 'H'
AND A.NACIMIENTO < TO_DATE('01-01-1070','DD-MM-YYYY');


--2

SELECT  C.PESO, C.TALLA, C.PEZ
FROM CAPTURASEVENTOS c 
WHERE C.PESO <= 45
ORDER BY C.PEZ DESC, C.PESO DESC, C.TALLA DESC;


--3

SELECT A.NOMBRE, A.APELLIDOS
FROM AFILIADOS a 
JOIN PERMISOS p ON P.FICHA =A.FICHA 
WHERE UPPER(P.LICENCIA) LIKE 'A%'
AND A.TELF LIKE '9%'
AND UPPER(A.DIRECCION) LIKE '%AVDA%' ;


--4

SELECT DISTINCT L.CAUCE, L.LUGAR, L.COMUNIDAD
FROM LUGARES l 
JOIN EVENTOS e ON E.LUGAR = L.LUGAR
JOIN CAPTURASSOLOS c ON C.LUGAR = E.LUGAR
WHERE UPPER(C.PEZ) LIKE 'TENCA';


--5

SELECT  A.NOMBRE, A.APELLIDOS 
FROM AFILIADOS a 
JOIN PARTICIPACIONES p ON P.FICHA = A.FICHA
JOIN EVENTOS e ON E.EVENTO = P.EVENTO
WHERE P.TROFEO IS NOT NULL
ORDER BY E.FECHA_EVENTO ASC;


--6

SELECT  A.NOMBRE, A.APELLIDOS
FROM AFILIADOS a 
JOIN CAPTURASSOLOS c ON C.AVAL1  = A.FICHA;


SELECT * FROM CAPTURASSOLOS c ;

--7 

SELECT  E.EVENTO
FROM  EVENTOS e 
JOIN PARTICIPACIONES p ON P.EVENTO = E.EVENTO
WHERE P.FICHA = '3796'
AND P.TROFEO IS NULL
ORDER BY E.FECHA_EVENTO DESC;


--8

SELECT COUNT(DISTINCT C.PEZ)
FROM CAPTURASSOLOS c ;


--9

SELECT  C.CAUCE
FROM CAUCES c 
JOIN LUGARES l ON L.CAUCE = C.CAUCE
GROUP BY c.CAUCE 
HAVING COUNT(L.LUGAR) > 1;



--10

SELECT L.LUGAR
FROM LUGARES l
JOIN EVENTOS e ON E.LUGAR = L.LUGAR
GROUP BY L.LUGAR
HAVING COUNT(E.EVENTO) < 1;


--11

SELECT  COUNT(C.PEZ) NUMERO_CAPTURAS,L.CAUCE
FROM CAPTURASEVENTOS c
JOIN EVENTOS e ON E.EVENTO = C.EVENTO
JOIN LUGARES l ON L.LUGAR = E.LUGAR
GROUP BY L.CAUCE
ORDER BY L.CAUCE ASC , COUNT(C.PEZ) ASC ;


--12

SELECT A.NOMBRE
FROM AFILIADOS a 
JOIN CAPTURASSOLOS c ON C.FICHA = A.FICHA
GROUP BY A.NOMBRE
HAVING COUNT(C.LUGAR) > 9;

--13

SELECT  E.EVENTO
FROM EVENTOS e 
JOIN PARTICIPACIONES p ON P.EVENTO = E.EVENTO
GROUP BY E.EVENTO
HAVING COUNT(P.FICHA) > 10;

--14

SELECT A.NOMBRE, A.APELLIDOS
FROM CAPTURASSOLOS c 
JOIN AFILIADOS a ON A.FICHA = C.AVAL1
JOIN AFILIADOS a ON A.FICHA = C.AVAL2;


SELECT * FROM CAPTURASSOLOS c ;

--15

SELECT A.NOMBRE, A.APELLIDOS,P.EVENTO PARTICIPACIONES
FROM AFILIADOS a 
RIGHT JOIN PARTICIPACIONES p ON P.FICHA = A.FICHA;


--16

SELECT A.NOMBRE
FROM AFILIADOS a 
JOIN PARTICIPACIONES p ON P.FICHA =A.FICHA
JOIN EVENTOS e ON E.EVENTO = P.EVENTO
JOIN CAPTURASEVENTOS c ON C.EVENTO = E.EVENTO
GROUP BY A.NOMBRE
HAVING COUNT(C.PEZ) < 1;



--17

SELECT AVG(C.PESO),AVG(C.TALLA)
FROM CAPTURASSOLOS c 
JOIN AFILIADOS a ON C.FICHA = A.FICHA;

























