CREATE TABLE TEMA (
    COD_TEMA NUMBER(10),
    DENOMINACION VARCHAR2(100) NOT NULL,
    COD_TEMA_PADRE NUMBER(10),
    CONSTRAINT CK_TEMA_PADRE CHECK (COD_TEMA_PADRE >= COD_TEMA)
);

CREATE TABLE AUTOR (
    COD_AUTOR NUMBER(10),
    NOMBRE VARCHAR2(100) NOT NULL,
    F_NACIMIENTO DATE,
    LIBRO_PRINCIPAL NUMBER(10)
);

CREATE TABLE LIBRO (
    COD_LIBRO NUMBER(10),
    TITULO VARCHAR2(100) NOT NULL,
    F_CREACION DATE,
    COD_TEMA NUMBER(10),
    AUTOR_PRINCIPAL NUMBER(10)
);

CREATE TABLE LIBRO_AUTOR (
    COD_LIBRO NUMBER(10),
    COD_AUTOR NUMBER(10),
    ORDEN NUMBER(10) CHECK (ORDEN BETWEEN 1 AND 5)
);

CREATE TABLE PUBLICACIONES (
    COD_EDITORIAL NUMBER(10),
    COD_LIBRO NUMBER(10),
    PRECIO NUMBER(10) NOT NULL CHECK (PRECIO > 0),
    F_PUBLICACION DATE DEFAULT SYSDATE
);

CREATE TABLE EDITORIAL (
    COD_EDITORIAL NUMBER(10),
    DENOMINACION VARCHAR2(100) NOT NULL
);

ALTER TABLE TEMA ADD CONSTRAINT PK_TEMA PRIMARY KEY (COD_TEMA);
ALTER TABLE AUTOR ADD CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR);
ALTER TABLE LIBRO ADD CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO);
ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO, COD_AUTOR);
ALTER TABLE PUBLICACIONES ADD CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (COD_EDITORIAL, COD_LIBRO);
ALTER TABLE EDITORIAL ADD CONSTRAINT PK_EDITORIAL PRIMARY KEY (COD_EDITORIAL);

ALTER TABLE TEMA
ADD CONSTRAINT FK_TEMA_PADRE FOREIGN KEY (COD_TEMA_PADRE)
REFERENCES TEMA (COD_TEMA);

ALTER TABLE AUTOR
ADD CONSTRAINT FK_LIBRO_PRINCIPAL FOREIGN KEY (LIBRO_PRINCIPAL)
REFERENCES LIBRO (COD_LIBRO);

ALTER TABLE LIBRO
ADD CONSTRAINT FK_LIBRO_TEMA FOREIGN KEY (COD_TEMA)
REFERENCES TEMA (COD_TEMA);

ALTER TABLE LIBRO
ADD CONSTRAINT FK_LIBRO_AUTOR_PRINCIPAL FOREIGN KEY (AUTOR_PRINCIPAL)
REFERENCES AUTOR (COD_AUTOR) ON DELETE RESTRICT;

ALTER TABLE LIBRO_AUTOR
ADD CONSTRAINT FK_LIBROAUTOR_LIBRO FOREIGN KEY (COD_LIBRO)
REFERENCES LIBRO (COD_LIBRO);

ALTER TABLE LIBRO_AUTOR
ADD CONSTRAINT FK_LIBROAUTOR_AUTOR FOREIGN KEY (COD_AUTOR)
REFERENCES AUTOR (COD_AUTOR);

ALTER TABLE PUBLICACIONES
ADD CONSTRAINT FK_PUBLICACIONES_LIBRO FOREIGN KEY (COD_LIBRO)
REFERENCES LIBRO (COD_LIBRO);

ALTER TABLE PUBLICACIONES
ADD CONSTRAINT FK_PUBLICACIONES_EDITORIAL FOREIGN KEY (COD_EDITORIAL)
REFERENCES EDITORIAL (COD_EDITORIAL) ON DELETE CASCADE;


