/* CREACIÓN DE TABLAS */

CREATE TABLE CABALLOS 
(
COD_CABALLO VARCHAR2(4),
NOMBRE VARCHAR2(20) NOT NULL,
PESO NUMBER(3),
FECHA_NACIMIENTO DATE,
PROPIETARIO VARCHAR2(25),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_CABALLO PRIMARY KEY (COD_CABALLO)
);

CREATE TABLE CARRERAS
(
COD_CARRERA VARCHAR2(4),
FECHA_HORA DATE,
IMPORTE_PREMIO NUMBER(6),
APUESTA_LIMITE NUMBER(5,2),
CONSTRAINT PK_CARRERAS PRIMARY KEY (COD_CARRERA)
);

CREATE TABLE CLIENTES 
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);

CREATE TABLE PARTICIPACIONES
(
COD_CABALLO VARCHAR2(4),
COD_CARRERA VARCHAR2(4),
DORSAL NUMBER(2)NOT NULL,
JOCKEY VARCHAR2(10) NOT NULL,
POSICION_FINAL NUMBER(2),
CONSTRAINT PK_PARTICIPACIONES PRIMARY KEY (COD_CABALLO,COD_CARRERA),
CONSTRAINT FK1_PARTICIPACIONES FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO),
CONSTRAINT FK2_PARTICIPACIONES FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA)
);

CREATE TABLE APUESTAS
(
DNI_CLIENTE VARCHAR2(10),
COD_CABALLO VARCHAR2(4),
COD_CARRERA VARCHAR2(4),
IMPORTE NUMBER(6)DEFAULT 300 NOT NULL,
TANTOPORTURNO NUMBER(4,2)NOT NULL,
CONSTRAINT PK_APUESTA PRIMARY KEY (DNI_CLIENTE,COD_CABALLO,COD_CARRERA),
CONSTRAINT FK1_APUESTA FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI),
CONSTRAINT FK2_APUESTA FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO),
CONSTRAINT FK3_APUESTA FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA)
);


/*CHECKS*/

ALTER TABLE CABALLOS ADD CONSTRAINT  CHK_PESO CHECK (PESO BETWEEN 240 AND 300);

ALTER TABLE CABALLOS ADD CONSTRAINT CHK_FECHA_NACIMIENTO CHECK (FECHA_NACIMIENTO > TO_DATE('01-01-2000','DD-MM-YYYY'));

ALTER TABLE CABALLOS ADD CONSTRAINT CHK_NACIONALIDAD_CABALLOS CHECK (NACIONALIDAD = UPPER(NACIONALIDAD)); 

ALTER TABLE PARTICIPACIONES ADD CONSTRAINT CHK_PRECIO CHECK (POSICION_FINAL >= 0);

ALTER TABLE CARRERAS ADD CONSTRAINT CHK_APUESTA_LIITE CHECK (APUESTA_LIMITE < 20000);

ALTER TABLE CLIENTES ADD CONSTRAINT CHK_NACIONALIDAD_CLIENTES CHECK (NACIONALIDAD = UPPER(NACIONALIDAD));

ALTER TABLE CLIENTES ADD CONSTRAINT CHK_DNI CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}[A-Z]$'));

ALTER TABLE CARRERAS  ADD CONSTRAINT chk_fecha_hora CHECK (
    EXTRACT(HOUR FROM Fecha_Hora) BETWEEN 9 AND 14 
    AND NOT (EXTRACT(HOUR FROM Fecha_Hora) = 14 AND EXTRACT(MINUTE FROM Fecha_Hora) > 30));


/*INSERTS*/

--2

INSERT INTO CLIENTES (DNI,NACIONALIDAD)
VALUES ('12345678N','ESCOCÉS');

INSERT INTO CABALLOS (COD_CABALLO,NOMBRE)
VALUES ('CAB1','Caballo Gigante');

INSERT INTO CARRERAS (COD_CARRERA, FECHA_HORA)
VALUES ('CAR1', TO_DATE('01-06-2009 10:00', 'DD-MM-YYYY HH24:MI'));

INSERT INTO PARTICIPACIONES (COD_CABALLO,COD_CARRERA,DORSAL,JOCKEY)
VALUES ('CAB1','CAR1',7,'Juan');

--3

INSERT INTO CABALLOS (COD_CABALLO,NOMBRE,NACIONALIDAD)
VALUES ('CAB2','Relampago','ESPAÑOL');

INSERT INTO CABALLOS (COD_CABALLO,NOMBRE,NACIONALIDAD)
VALUES ('CAB3','Pulgas','ÁRABE');

INSERT INTO CARRERAS (COD_CARRERA)
VALUES ('C6');

INSERT INTO PARTICIPACIONES (COD_CABALLO,COD_CARRERA,DORSAL,JOCKEY)
VALUES ('CAB2','C6',10,'Andrés');

INSERT INTO PARTICIPACIONES (COD_CABALLO,COD_CARRERA,DORSAL,JOCKEY)
VALUES ('CAB3','C6',5,'Jhon');


--4

INSERT INTO CARRERAS (COD_CARRERA,FECHA_HORA,IMPORTE_PREMIO)
VALUES ('CAR2',TO_DATE('05-10-2010 10:30','DD-MM-YYYY HH24:MI'),200);

INSERT INTO CARRERAS (COD_CARRERA,FECHA_HORA,IMPORTE_PREMIO)
VALUES ('CAR3',TO_DATE('06-10-2010 10:30','DD-MM-YYYY HH24:MI'),400);






































