/*CREACION DE TABLAS*/

CREATE TABLE DEPARTAMENTO
(
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),
PRESUPUESTO NUMBER(10,2),
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO 
(
CODIGO NUMBER(10),
NIF  VARCHAR2(9),
NOMBRE VARCHAR2(100),
APPELLIDO1 VARCHAR2(100),
APELLIDO2 VARCHAR2(100),
CODIGO_DEPARTAMENTO NUMBER(10),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO),
CONSTRAINT FK_EMPLEADO FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
);

/*INSERTS DEPARTAMENTO*/

INSERT INTO DEPARTAMENTO
VALUES (1, 'Desarrollo', 120000);

INSERT INTO DEPARTAMENTO
VALUES (2, 'Sistemas', 150000);

INSERT INTO DEPARTAMENTO
VALUES (3, 'Recursos Humanos', 280000);

INSERT INTO DEPARTAMENTO
VALUES (4, 'Contabilidad', 110000);

INSERT INTO DEPARTAMENTO
VALUES (5, 'I+D', 375000);

INSERT INTO DEPARTAMENTO
VALUES (6, 'Proyectos', 0);

INSERT INTO DEPARTAMENTO
VALUES (7, 'Publicidad', 0);



/*INSERTS DE EMPLEADOS*/

INSERT INTO EMPLEADO
VALUES (1, '32481596F', 'Aarón', 'Rivero', 'Gómez', 1);

INSERT INTO EMPLEADO
VALUES (2, 'Y5575632D', 'Adela', 'Salas', 'Díaz', 2);

INSERT INTO EMPLEADO
VALUES (3, 'R6970642B', 'Adolfo', 'Rubio', 'Flores', 3);

INSERT INTO EMPLEADO
VALUES (4, '77705545E', 'Adrián', 'Suárez', NULL, 4);

INSERT INTO EMPLEADO
VALUES (5, '17087203C', 'Marcos', 'Loyola', 'Méndez', 5);

INSERT INTO EMPLEADO
VALUES (6, '38382980M', 'María', 'Santana', 'Moreno', 1);

INSERT INTO EMPLEADO
VALUES (7, '80576669X', 'Pilar', 'Ruiz', NULL, 2);

INSERT INTO EMPLEADO
VALUES (8, '71651431Z', 'Pepe', 'Ruiz', 'Santana', 3);

INSERT INTO EMPLEADO
VALUES (9, '56399183D', 'Juan', 'Gómez', 'López', 2);

INSERT INTO EMPLEADO
VALUES (10, '46384486H', 'Diego','Flores', 'Salas', 5);

INSERT INTO EMPLEADO
VALUES (11, '67389283A', 'Marta','Herrera', 'Gil', 1);

INSERT INTO EMPLEADO
VALUES (12, '41234836R', 'Irene','Salas', 'Flores', NULL);

INSERT INTO EMPLEADO
VALUES (13, '82635162B', 'Juan Antonio','Sáez', 'Guerrero', NULL);



--1 Inserta un nuevo departamento indicando
--su código, nombre y presupuesto.

INSERT INTO DEPARTAMENTO
VALUES (8,'Recursos Humanos',10000);

--2 Inserta un nuevo departamento indicando su nombre y presupuesto.

CREATE SEQUENCE SQN_DEPARTAMENTO
START WITH 9
INCREMENT BY 1;

INSERT INTO DEPARTAMENTO
VALUES (SQN_DEPARTAMENTO.NEXTVAL,'Limpieza',1000);

--3 Inserta un nuevo departamento indicando
--su código, nombre, presupuesto y gastos.

ALTER TABLE DEPARTAMENTO ADD GASTOS NUMBER(10,2);

INSERT INTO DEPARTAMENTO
VALUES (SQN_DEPARTAMENTO.NEXTVAL,'Seguridad',50000,25000);

SELECT * FROM DEPARTAMENTO;






