/*CREACION DE TABLAS*/

CREATE TABLE ALUMNOS
(
NOMBRE VARCHAR2(25),
APELLIDO1 VARCHAR2(25),
APELLIDO2 VARCHAR2(25),
DNI VARCHAR2(10),
DIRECCION VARCHAR2(50),
SEXO VARCHAR2(10),
FECHA_NACIMNIENTO DATE,
CURSO NUMBER(10),
CONSTRAINT PK_ALUMNO PRIMARY KEY (DNI)
);

CREATE TABLE PROFESORES
(
NOMBRE VARCHAR2(25),
APELLIDO1 VARCHAR(25),
APELLIDO2 VARCHAR(25),
DNI VARCHAR2(10),
DIRECCION VARCHAR2(50),
TITULO VARCHAR2(25),
GANA NUMBER(10),
CONSTRAINT PK_PROFESORES PRIMARY KEY (DNI)
);

CREATE TABLE CURSO 
(
NOMBRE_CURSO VARCHAR2(25),
COD_CURSO VARCHAR2(25),
DNI_PROFESOR VARCHAR2(10),
MAXIMO_ALUMNOS NUMBER(10),
FECHA_INICIO DATE,
FECHA_FIN DATE,
NUM_HORAS NUMBER,
CONSTRAINT PK_CURSO PRIMARY KEY (COD_CURSO),
CONSTRAINT FK1_CURSO FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI)
);



/*INSERCION DE DATOS EN TABLAS*/

SELECT * FROM PROFESORES;

INSERT INTO PROFESORES 
VALUES ('Juan','Arch','López','32432455','Puerta Negra, 4','Ing.Informatica',7500);

INSERT INTO profesores
VALUES ('María','Olivia','Rubio','43215643','juan Alfonso 32','Lda.Fil.Inglesa',5400);

SELECT * FROM CURSO;

INSERT INTO CURSO
VALUES ('Inglés básico','1','43215643',15,TO_date('01/11/2000','dd-mm-yyyy'),to_date('22/12/2000','dd-mm-yyyy'),120 );

INSERT INTO CURSO (NOMBRE_CURSO,COD_CURSO,DNI_PROFESOR,FECHA_INICIO,NUM_HORAS)
VALUES ('','2')












