/*CREACION DE TABLAS*/

CREATE TABLE ALUMNOS
(
NOMBRE VARCHAR2(25),
APELLIDO1 VARCHAR2(25),
APELLIDO2 VARCHAR2(25),
DNI VARCHAR2(10),
DIRECCION VARCHAR2(50),
SEXO VARCHAR2(10),
FECHA_NACIMNIENTO DATE,
CURSO NUMBER(10),
CONSTRAINT PK_ALUMNO PRIMARY KEY (DNI)
);

CREATE TABLE PROFESORES
(
NOMBRE VARCHAR2(25),
APELLIDO1 VARCHAR(25),
APELLIDO2 VARCHAR(25),
DNI VARCHAR2(10),
DIRECCION VARCHAR2(50),
TITULO VARCHAR2(25),
GANA NUMBER(10),
CONSTRAINT PK_PROFESORES PRIMARY KEY (DNI)
);

CREATE TABLE CURSO 
(
NOMBRE_CURSO VARCHAR2(25),
COD_CURSO VARCHAR2(25),
DNI_PROFESOR VARCHAR2(10),
MAXIMO_ALUMNOS NUMBER(10),
FECHA_INICIO DATE,
FECHA_FIN DATE,
NUM_HORAS NUMBER,
CONSTRAINT PK_CURSO PRIMARY KEY (COD_CURSO),
CONSTRAINT FK1_CURSO FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI)
);



/*INSERCION DE DATOS EN TABLAS*/

SELECT * FROM PROFESORES;

INSERT INTO PROFESORES 
VALUES ('Juan','Arch','López','32432455','Puerta Negra, 4','Ing.Informatica',7500);

INSERT INTO profesores
VALUES ('María','Olivia','Rubio','43215643','juan Alfonso 32','Lda.Fil.Inglesa',5400);

SELECT * FROM CURSO;

INSERT INTO CURSO
VALUES ('Inglés básico','1','43215643',15,TO_date('01/11/2000','dd-mm-yyyy'),to_date('22/12/2000','dd-mm-yyyy'),120 );

INSERT INTO CURSO (NOMBRE_CURSO,COD_CURSO,DNI_PROFESOR,FECHA_INICIO,NUM_HORAS)
VALUES ('Administracion Linux','2','32432455',to_date('01-10-2000','dd-mm-yyyy'),80);

SELECT * FROM ALUMNOS;

INSERT INTO ALUMNOS
VALUES ('Lucas','Manilva','Lopez','123523','Alhamar,3','v',to_date('01-11-1979','dd-mm-yyyy'),1);

INSERT INTO ALUMNOS (NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,CURSO)
VALUES ('Antonia','Lopez','Alcantara','2567567','Maniqui,21','m',2);

INSERT INTO ALUMNOS (NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,CURSO)
VALUES ('Manuel','Alcantara','Pedros','3123689','Julian,2','v',1);

INSERT INTO ALUMNOS
VALUES ('Jose','Perez','Caballar','4896765','Jarcha,5','v',to_date('03-02-1977','dd-mm-yyyy'),3);

INSERT INTO PROFESORES (NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,TITULO)
VALUES ('Juan','Arch','Lopez','324325','Puerta Negra,4','Ing.Informatica');

INSERT INTO ALUMNOS (NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO)
VALUES ('Maria','jaen','Sevilla','789678','martos,5','m');

/*MODIFICACIONES*/

UPDATE ALUMNOS
SET FECHA_NACIMNIENTO = TO_DATE('23-12-1976', 'DD-MM-YYYY')
WHERE DNI = '2567567';

UPDATE ALUMNOS 
SET CURSO = 5
WHERE DNI = '2567567';

DELETE FROM CURSO
WHERE COD_CURSO = '1';

ALTER TABLE CURSO ADD NUMERO_ALUMNOS NUMBER(10);

UPDATE  ALUMNOS 
SET FECHA_NACIMNIENTO = TO_DATE('01-01-2012','DD-MM-YYYY')
WHERE FECHA_NACIMNIENTO IS NULL;

ALTER TABLE ALUMNOS 
DROP COLUMN SEXO;

UPDATE PROFESORES 
SET GANA = GANA*1.20
WHERE TITULO = 'Ing.Informatica';

/*
UPDATE PROFESORES
SET DNI = '1234567'
WHERE NOMBRE = 'Juan' AND APELLIDO1 = 'Arch';
*/
/*
UPDATE ALUMNOS 
SET SEXO = 'f'
WHERE NOMBRE = 'Maria' AND APELLIDO1 = 'Jaen';
*/







