/*CREATE DATABASE PRUEBAJAVIERROLDAN;*/

/*CREACION DE TABLAS*/

CREATE TABLE FAMILIA (
    NOMBRE VARCHAR(20),
    CARACTERISTICAS VARCHAR(25),
    CONSTRAINT PK_FAMILIA PRIMARY KEY (NOMBRE)
);

CREATE TABLE GENERO (
    NOMBRE VARCHAR(20),
    CARACTERISTICAS VARCHAR(25),
    NOMBRE_FAMILIA VARCHAR(20),
    CONSTRAINT PK_GENERO PRIMARY KEY (NOMBRE),
    CONSTRAINT FK1_GENERO FOREIGN KEY (NOMBRE_FAMILIA) REFERENCES FAMILIA(NOMBRE)
);

CREATE TABLE ESPECIE (
    NOMBRE VARCHAR(20),
    CARACTERISTICAS VARCHAR(25),
    NOMBRE_GENERO VARCHAR(20),
    CONSTRAINT PK_ESPECIE PRIMARY KEY (NOMBRE),
    CONSTRAINT FK1_ESPECIE FOREIGN KEY (NOMBRE_GENERO) REFERENCES GENERO(NOMBRE) ON DELETE CASCADE
);

CREATE TABLE PERSONA (
    DNI VARCHAR(10),
    NOMBRE VARCHAR(20),
    DIRECCION VARCHAR(30),
    TELEFONO BIGINT,
    USUARIO VARCHAR(20) UNIQUE,
    CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
);

CREATE TABLE ZONA (
    NOMBRE VARCHAR(20),
    LOCALIDAD VARCHAR(25),
    EXTENSION INT,
    PROTEGIDA VARCHAR(10),
    CONSTRAINT PK_ZONA PRIMARY KEY (NOMBRE)
);

CREATE TABLE COLECCION (
    DNI_PERSONA VARCHAR(10),
    PRECIO DECIMAL(15,2),
    FECHA_INICIO DATE,
    N_EJEMPLAR INT,
    CONSTRAINT PK_COLECCION PRIMARY KEY (DNI_PERSONA),
    CONSTRAINT FK1_COLECCION FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA(DNI)
);

CREATE TABLE EJEMPLAR_MARIPOSA (
    FECHA_CAPTURA DATE,
    HORA_CAPTURA INT,
    NOMBRE_COMUN VARCHAR(20),
    PRECIO_EJEMPLAR DECIMAL(20,2),
    NOMBRE_ZONA VARCHAR(20),
    DNI_PERSONA VARCHAR(10),
    FECHA_COLECCION DATE,
    NOMBRE_ESPECIE VARCHAR(20),
    DNI_COLECCION VARCHAR(10),
    CONSTRAINT PK_EJEMPLAR_MARIPOSA PRIMARY KEY (FECHA_CAPTURA, HORA_CAPTURA, DNI_PERSONA, NOMBRE_ZONA, NOMBRE_ESPECIE),
    CONSTRAINT FK1_EJEMPLAR_MARIPOSA FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA(DNI),
    CONSTRAINT FK2_EJEMPLAR_MARIPOSA FOREIGN KEY (NOMBRE_ZONA) REFERENCES ZONA(NOMBRE),
    CONSTRAINT FK3_EJEMPLAR_MARIPOSA FOREIGN KEY (NOMBRE_ESPECIE) REFERENCES ESPECIE(NOMBRE),
    CONSTRAINT FK4_EJEMPLAR_MARIPOSA FOREIGN KEY (DNI_COLECCION) REFERENCES COLECCION(DNI_PERSONA)
);

/* RESTRICCIONES */
ALTER TABLE EJEMPLAR_MARIPOSA ADD CONSTRAINT CHK_PRECIO_EJEMPLAR CHECK (PRECIO_EJEMPLAR > 0);

ALTER TABLE ZONA ADD CONSTRAINT CHK_PROTEGIDA CHECK (PROTEGIDA IN ('SI', 'NO'));

ALTER TABLE COLECCION ADD CONSTRAINT CHK_CANT_EJEMPLAR CHECK (N_EJEMPLAR >= 1 AND N_EJEMPLAR <= 150);

ALTER TABLE EJEMPLAR_MARIPOSA ADD CONSTRAINT CHK_FECHA_CAPTURA CHECK (FECHA_CAPTURA >= '2023-01-01');

ALTER TABLE PERSONA ADD APELLIDOS VARCHAR(20);

ALTER TABLE EJEMPLAR_MARIPOSA DROP CHECK CHK_PRECIO_EJEMPLAR;








