/*alter session set "_oracle_script"=true;  
create user PRUEBAJAVIERROLDAN identified by PRUEBAJAVIERROLDAN;
GRANT CONNECT, RESOURCE, DBA TO PRUEBAJAVIERROLDAN;*/


/*CREACION DE TABLAS*/

CREATE TABLE FAMILIA 
(
NOMBRE VARCHAR2(20),
CARACTERISTICAS VARCHAR2(25),
CONSTRAINT PK_FAMILIA PRIMARY KEY (NOMBRE)
);

CREATE TABLE GENERO
(
NOMBRE VARCHAR2(20),
CARACTERISTICAS VARCHAR2(25),
NOMBRE_FAMILIA VARCHAR2(20),
CONSTRAINT PK_GENERO PRIMARY KEY (NOMBRE),
CONSTRAINT FK1_GENERO FOREIGN KEY (NOMBRE_FAMILIA) REFERENCES FAMILIA(NOMBRE)
);

CREATE TABLE ESPECIE
(
NOMBRE VARCHAR2(20),
CARACTERISTICAS VARCHAR2(25),
NOMBRE_GENERO VARCHAR2(20),
CONSTRAINT PK_ESPECIE PRIMARY KEY (NOMBRE),
CONSTRAINT FK1_ESPECIE FOREIGN KEY (NOMBRE_GENERO) REFERENCES GENERO(NOMBRE) ON DELETE CASCADE
);

CREATE TABLE PERSONA
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
DIRECCION VARCHAR2(30),
TELEFONO NUMBER(10),
USUARIO VARCHAR2(20) UNIQUE,
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
);

CREATE TABLE ZONA
(
NOMBRE VARCHAR2(20),
LOCALIDAD VARCHAR2(25),
EXTENSION NUMBER(20),
PROTEGIDA VARCHAR2(10),
CONSTRAINT PK_ZONA PRIMARY KEY (NOMBRE)
);

CREATE TABLE COLECCION
(
DNI_PERSONA VARCHAR2(10),
PRECIO NUMBER(15),
FECHA_INICIO DATE,
N_EJEMPLAR NUMBER(20),
CONSTRAINT PK_COLECCION PRIMARY KEY (DNI_PERSONA),
CONSTRAINT FK1_COLECCION FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA(DNI)
);

CREATE TABLE EJEMPLAR_MARIPOSA
(
FECHA_CAPTURA DATE,
HORA_CAPTURA NUMBER(10),
NOMBRE_COMUN VARCHAR2(20),
PRECIO_EJEMPLAR NUMBER(20),
NOMBRE_ZONA VARCHAR2(20),
DNI_PERSONA VARCHAR2(10),
FECHA_COLECCION DATE,
NOMBRE_ESPECIE VARCHAR2(20),
DNI_COLECCION VARCHAR2(10),
CONSTRAINT PK_EJEMPLAR_MARIPOSA PRIMARY KEY (FECHA_CAPTURA,HORA_CAPTURA,DNI_PERSONA,NOMBRE_ZONA,NOMBRE_ESPECIE),
CONSTRAINT  FK1_EJEMPLAR_MARIPOSA FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA(DNI),
CONSTRAINT  FK2_EJEMPLAR_MARIPOSA FOREIGN KEY (NOMBRE_ZONA) REFERENCES ZONA(NOMBRE),
CONSTRAINT  FK3_EJEMPLAR_MARIPOSA FOREIGN KEY (NOMBRE_ESPECIE) REFERENCES ESPECIE(NOMBRE),
CONSTRAINT  FK4_EJEMPLAR_MARIPOSA FOREIGN KEY (DNI_COLECCION) REFERENCES COLECCION(DNI_PERSONA)
);


/*RESTRICCIONES*/

ALTER TABLE EJEMPLAR_MARIPOSA ADD CONSTRAINT CHK_PRECIO_EJEMPLAR CHECK (PRECIO_EJEMPLAR > 0);

ALTER TABLE ZONA ADD CONSTRAINT CHK_PROTEGIDA CHECK (PROTEGIDA IN('SI','NO'));

ALTER TABLE COLECCION ADD CONSTRAINT CHK_CANT_EJEMPLAR CHECK (N_EJEMPLAR>=1 AND N_EJEMPLAR<=150);

ALTER TABLE EJEMPLAR_MARIPOSA ADD CONSTRAINT CHK_FECHA_CAPTURA CHECK (FECHA_CAPTURA >= TO_DATE('2023-01-01', 'YYYY-MM-DD'));

ALTER TABLE PERSONA ADD APELLIDOS VARCHAR2(20);

ALTER TABLE  EJEMPLAR_MARIPOSA DROP CONSTRAINT  CHK_PRECIO_EJEMPLAR;















